# Generated by Django 5.2.6 on 2025-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('is_completed', models.BooleanField(default=0, max_length=1)),
                ('complete_dt', models.DateField(default='')),
            ],
        ),
    ]
