# Generated by Django 5.2.6 on 2025-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_complete_dt_alter_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
